#version: '3.8'
#services:
#  stats-db:
#    image: postgres:14-alpine
#    container_name: stats-db
#    ports:
#      - "6541:5432"
#    environment:
#      - POSTGRES_DB=stats
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#
#  stats-server:
#    build: ewm-stats-service
##      context: ./ewm-stats-service
##      dockerfile: Dockerfile
#    container_name: stats-server
#    ports:
#      - "9099:9090"
#
#    depends_on:
#      - stats-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#
#  ewm-service:
#    build: ewm-main-service
##      context: ./ewm-main-service
##      dockerfile: Dockerfile
#    container_name: ewm-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ewm-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#      - EWM_STATS_SERVICE_URL=http://stats-server:9090
#
#  ewm-db:
#    image: postgres:14-alpine
#    container_name: ewm-db
#    ports:
#      - "6542:5432"
#    environment:
#      - POSTGRES_DB=main
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root

version: '3.8'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d stats"]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-server:
    build:
      context: ./ewm-stats-service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090"]
      interval: 10s
      timeout: 5s
      retries: 5

  ewm-service:
    build:
      context: ./ewm-main-service
      dockerfile: Dockerfile
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - EWM_STATS_SERVICE_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d main"]
      interval: 10s
      timeout: 5s
      retries: 5